/** GLORY Control Room — protected content operations in the established Altın Eşik system. */
import { type ReactNode, useEffect, useMemo, useState } from "react";
import { FileText, Globe2, LayoutDashboard, LockKeyhole, Network, Save, ShieldCheck, Sparkles, Type, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { cloneDefaultGloryContent, type GloryContent } from "@shared/gloryContent";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type TabId = "identity" | "content" | "contract" | "tokenomics" | "roadmap" | "whitepaper" | "community";

const tabs: Array<{ id: TabId; label: string; icon: typeof Sparkles }> = [
  { id: "identity", label: "Kimlik & Hero", icon: Sparkles },
  { id: "content", label: "Site İçeriği", icon: Type },
  { id: "contract", label: "Kontrat & Güven", icon: ShieldCheck },
  { id: "tokenomics", label: "Tokenomics", icon: Network },
  { id: "roadmap", label: "Roadmap", icon: LayoutDashboard },
  { id: "whitepaper", label: "Whitepaper", icon: FileText },
  { id: "community", label: "Topluluk", icon: UsersRound },
];

function Field({ label, value, onChange, multiline = false, type = "text", hint }: { label: string; value: string | number; onChange: (value: string) => void; multiline?: boolean; type?: string; hint?: string }) {
  const base = "mt-2 w-full rounded-none border border-white/10 bg-[#151411] px-3 py-2.5 text-sm text-[#f3eee5] outline-none transition focus:border-[#c6a66a] focus:ring-1 focus:ring-[#c6a66a]/35";
  return <label className="block"><span className="font-mono text-[10px] tracking-[0.12em] text-[#b9ad98]">{label}</span>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} className={`${base} min-h-28 resize-y leading-6`} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} className={base} />}{hint ? <span className="mt-1.5 block text-xs leading-5 text-[#77736c]">{hint}</span> : null}</label>;
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) {
  return <div className="grid gap-6"><div><p className="eyebrow">{eyebrow}</p><h2 className="heading-display mt-3 text-3xl">{title}</h2></div>{children}</div>;
}

function AdminGuard() {
  const { user, loading } = useAuth();
  const contentQuery = trpc.glory.get.useQuery();
  const utils = trpc.useUtils();
  const [draft, setDraft] = useState<GloryContent | null>(null);
  const [tab, setTab] = useState<TabId>("identity");
  const saveMutation = trpc.glory.save.useMutation({ onSuccess: async () => { await utils.glory.get.invalidate(); toast.success("Changes published", { description: "The GLORY public site now uses the saved configuration." }); }, onError: (error) => toast.error("Unable to save", { description: error.message }) });

  useEffect(() => { if (contentQuery.data) setDraft(structuredClone(contentQuery.data)); }, [contentQuery.data]);
  const update = (recipe: (content: GloryContent) => void) => setDraft((current) => { const next = structuredClone(current ?? cloneDefaultGloryContent()); recipe(next); return next; });
  const allocationTotal = useMemo(() => draft?.tokenomics.allocations.reduce((sum, item) => sum + Number(item.percentage || 0), 0) ?? 0, [draft]);

  if (loading || contentQuery.isLoading || !draft) return <div className="min-h-[65vh] animate-pulse bg-[#121210]" />;
  if (user?.role !== "admin") return <section className="mx-auto flex min-h-[65vh] max-w-2xl items-center justify-center"><div className="max-w-md border border-[#c6a66a]/25 bg-[#151411] p-8 text-center"><LockKeyhole className="mx-auto h-7 w-7 text-[#c6a66a]" /><p className="eyebrow mt-6">RESTRICTED ACCESS</p><h1 className="heading-display mt-4 text-4xl">Administrator role required.</h1><p className="mt-5 text-sm leading-6 text-[#aaa69f]">This control room can only be opened by an authorized GLORY administrator.</p><Link href="/" className="glory-text-link mt-8 inline-flex font-mono text-[10px] tracking-[0.14em]">RETURN TO GLORY</Link></div></section>;

  const save = () => saveMutation.mutate(draft);
  return <div className="mx-auto max-w-6xl pb-16"><div className="flex flex-col gap-6 border-b border-white/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">GLORY / CONTROL ROOM</p><h1 className="heading-display mt-4 text-4xl text-[#f3eee5] sm:text-5xl">Publish with <span className="text-[#c6a66a]">precision.</span></h1><p className="mt-4 max-w-2xl leading-7 text-[#9f9b93]">Manage the approved public content, technical disclosure, roadmap, whitepaper and official community destinations without touching the public design system.</p></div><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={() => setDraft(cloneDefaultGloryContent())} className="glory-button-outline rounded-none font-mono text-[10px] tracking-[0.12em]">RESTORE DEFAULT DRAFT</Button><Button onClick={save} disabled={saveMutation.isPending} className="glory-button-gold rounded-none font-mono text-[10px] tracking-[0.12em]"><Save className="mr-2 h-3.5 w-3.5" />{saveMutation.isPending ? "SAVING" : "SAVE & PUBLISH"}</Button></div></div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[220px_1fr]"><nav className="flex gap-2 overflow-x-auto lg:flex-col">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-3 border px-3 py-3 text-left font-mono text-[10px] tracking-[0.1em] transition ${tab === id ? "border-[#c6a66a]/55 bg-[#c6a66a]/10 text-[#ead9b3]" : "border-white/10 text-[#85817b] hover:border-white/25 hover:text-[#e6dfd2]"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
      <section className="border border-white/10 bg-[#121210] p-5 sm:p-8">
        {tab === "identity" && <Panel eyebrow="IDENTITY & HERO" title="Public narrative"><div className="grid gap-5 md:grid-cols-2"><Field label="BRAND NAME" value={draft.brand.name} onChange={(value) => update((content) => { content.brand.name = value; })} /><Field label="TOKEN SYMBOL" value={draft.brand.symbol} onChange={(value) => update((content) => { content.brand.symbol = value; })} /><Field label="EYEBROW" value={draft.hero.eyebrow} onChange={(value) => update((content) => { content.hero.eyebrow = value; })} /><Field label="TAGLINE" value={draft.brand.tagline} onChange={(value) => update((content) => { content.brand.tagline = value; })} /><Field label="HERO LINE 01" value={draft.hero.lineOne} onChange={(value) => update((content) => { content.hero.lineOne = value; })} /><Field label="HERO LINE 02" value={draft.hero.lineTwo} onChange={(value) => update((content) => { content.hero.lineTwo = value; })} /><Field label="HERO LINE 03" value={draft.hero.lineThree} onChange={(value) => update((content) => { content.hero.lineThree = value; })} /></div><Field label="HERO DESCRIPTION" value={draft.hero.body} multiline onChange={(value) => update((content) => { content.hero.body = value; })} /></Panel>}
        {tab === "content" && <Panel eyebrow="PUBLIC COPY" title="Site content"><div className="grid gap-5"><Field label="FOUNDATION TITLE" value={draft.foundation.title} onChange={(value) => update((content) => { content.foundation.title = value; })} /><Field label="FOUNDATION DESCRIPTION" value={draft.foundation.body} multiline onChange={(value) => update((content) => { content.foundation.body = value; })} />{draft.foundation.pillars.map((pillar, index) => <div key={pillar.number} className="grid gap-4 border border-white/10 p-4 md:grid-cols-[90px_1fr_1fr]"><Field label="INDEX" value={pillar.number} onChange={(value) => update((content) => { content.foundation.pillars[index].number = value; })} /><Field label="TITLE" value={pillar.title} onChange={(value) => update((content) => { content.foundation.pillars[index].title = value; })} /><Field label="DESCRIPTION" value={pillar.body} multiline onChange={(value) => update((content) => { content.foundation.pillars[index].body = value; })} /></div>)}<div className="border-t border-white/10 pt-6"><div className="grid gap-5"><Field label="ECOSYSTEM TITLE" value={draft.ecosystem.title} onChange={(value) => update((content) => { content.ecosystem.title = value; })} /><Field label="ECOSYSTEM DESCRIPTION" value={draft.ecosystem.body} multiline onChange={(value) => update((content) => { content.ecosystem.body = value; })} /><Field label="PRODUCT NAME" value={draft.ecosystem.productName} onChange={(value) => update((content) => { content.ecosystem.productName = value; })} /><Field label="TOKEN SECTION TITLE" value={draft.token.title} onChange={(value) => update((content) => { content.token.title = value; })} /><Field label="TOKEN SECTION DESCRIPTION" value={draft.token.body} multiline onChange={(value) => update((content) => { content.token.body = value; })} /></div></div></div></Panel>}
        {tab === "contract" && <Panel eyebrow="TECHNICAL DISCLOSURE" title="Contract & transparency"><div className="grid gap-5 md:grid-cols-2"><Field label="CONTRACT ADDRESS" value={draft.contract.address} onChange={(value) => update((content) => { content.contract.address = value; })} /><Field label="BSCSCAN URL" value={draft.contract.bscScanUrl} onChange={(value) => update((content) => { content.contract.bscScanUrl = value; })} /><Field label="NETWORK" value={draft.contract.network} onChange={(value) => update((content) => { content.contract.network = value; })} /><Field label="STANDARD" value={draft.contract.standard} onChange={(value) => update((content) => { content.contract.standard = value; })} /><Field label="DECIMALS" value={draft.contract.decimals} onChange={(value) => update((content) => { content.contract.decimals = value; })} /><Field label="TOTAL SUPPLY" value={draft.contract.totalSupply} onChange={(value) => update((content) => { content.contract.totalSupply = value; })} /><Field label="MINT AUTHORITY" value={draft.contract.mint} onChange={(value) => update((content) => { content.contract.mint = value; })} /><Field label="OWNER / ADMIN" value={draft.contract.owner} onChange={(value) => update((content) => { content.contract.owner = value; })} /><Field label="TAX" value={draft.contract.tax} onChange={(value) => update((content) => { content.contract.tax = value; })} /><Field label="BLACKLIST" value={draft.contract.blacklist} onChange={(value) => update((content) => { content.contract.blacklist = value; })} /><Field label="PAUSE" value={draft.contract.pause} onChange={(value) => update((content) => { content.contract.pause = value; })} /></div><div className="border-t border-white/10 pt-6"><div className="grid gap-5"><Field label="TRANSPARENCY TITLE" value={draft.transparency.title} onChange={(value) => update((content) => { content.transparency.title = value; })} /><Field label="TRANSPARENCY INTRO" value={draft.transparency.body} multiline onChange={(value) => update((content) => { content.transparency.body = value; })} />{draft.transparency.items.map((item, index) => <div key={item.title} className="grid gap-4 border border-white/10 p-4 md:grid-cols-2"><Field label="CARD TITLE" value={item.title} onChange={(value) => update((content) => { content.transparency.items[index].title = value; })} /><Field label="CARD DESCRIPTION" value={item.body} multiline onChange={(value) => update((content) => { content.transparency.items[index].body = value; })} /></div>)}</div></div></Panel>}
        {tab === "tokenomics" && <Panel eyebrow="PLANNED ALLOCATION" title="Tokenomics"><div className="grid gap-5"><Field label="SECTION TITLE" value={draft.tokenomics.title} onChange={(value) => update((content) => { content.tokenomics.title = value; })} /><Field label="SECTION DESCRIPTION" value={draft.tokenomics.body} multiline onChange={(value) => update((content) => { content.tokenomics.body = value; })} /></div><div className="mt-5 rounded-none border border-[#c6a66a]/30 bg-[#c6a66a]/5 p-4 font-mono text-[10px] tracking-[0.12em] text-[#ded3bc]">ALLOCATION TOTAL: <span className={allocationTotal === 100 ? "text-[#e6c986]" : "text-red-300"}>{allocationTotal}%</span></div><div className="mt-6 grid gap-4">{draft.tokenomics.allocations.map((item, index) => <div key={`${item.label}-${index}`} className="grid gap-3 border border-white/10 p-4 md:grid-cols-[1.5fr_90px_1fr_120px]"><Field label="LABEL" value={item.label} onChange={(value) => update((content) => { content.tokenomics.allocations[index].label = value; })} /><Field label="PERCENTAGE" type="number" value={item.percentage} onChange={(value) => update((content) => { content.tokenomics.allocations[index].percentage = Number(value) || 0; })} /><Field label="AMOUNT" value={item.amount} onChange={(value) => update((content) => { content.tokenomics.allocations[index].amount = value; })} /><Field label="HEX COLOR" value={item.tone} onChange={(value) => update((content) => { content.tokenomics.allocations[index].tone = value; })} /></div>)}</div></Panel>}
        {tab === "roadmap" && <Panel eyebrow="DELIVERY DIRECTION" title="Roadmap"><div className="grid gap-5"><Field label="SECTION TITLE" value={draft.roadmap.title} onChange={(value) => update((content) => { content.roadmap.title = value; })} /><Field label="SECTION DESCRIPTION" value={draft.roadmap.body} multiline onChange={(value) => update((content) => { content.roadmap.body = value; })} /></div><div className="mt-6 grid gap-4">{draft.roadmap.phases.map((phase, index) => <div key={phase.number} className="grid gap-4 border border-white/10 p-4"><div className="grid gap-4 md:grid-cols-3"><Field label="PHASE" value={phase.number} onChange={(value) => update((content) => { content.roadmap.phases[index].number = value; })} /><Field label="TITLE" value={phase.title} onChange={(value) => update((content) => { content.roadmap.phases[index].title = value; })} /><label className="block"><span className="font-mono text-[10px] tracking-[0.12em] text-[#b9ad98]">STATUS</span><select value={phase.status} onChange={(event) => update((content) => { content.roadmap.phases[index].status = event.target.value as GloryContent["roadmap"]["phases"][number]["status"]; })} className="mt-2 w-full border border-white/10 bg-[#151411] px-3 py-2.5 text-sm text-[#f3eee5] outline-none focus:border-[#c6a66a]"><option>COMPLETED</option><option>IN PROGRESS</option><option>PLANNED</option></select></label></div><Field label="MILESTONES — ONE PER LINE" value={phase.entries.join("\n")} multiline onChange={(value) => update((content) => { content.roadmap.phases[index].entries = value.split("\n").map((entry) => entry.trim()).filter(Boolean); })} /></div>)}</div></Panel>}
        {tab === "whitepaper" && <Panel eyebrow="WEB-NATIVE DOCUMENTATION" title="Whitepaper"><div className="grid gap-5"><Field label="VERSION LABEL" value={draft.whitepaper.version} onChange={(value) => update((content) => { content.whitepaper.version = value; })} /><Field label="TITLE" value={draft.whitepaper.title} onChange={(value) => update((content) => { content.whitepaper.title = value; })} /><Field label="LEAD" value={draft.whitepaper.lead} multiline onChange={(value) => update((content) => { content.whitepaper.lead = value; })} /><Field label="VERIFIED PDF URL (OPTIONAL)" value={draft.whitepaper.pdfUrl} onChange={(value) => update((content) => { content.whitepaper.pdfUrl = value; })} hint="A download action becomes visible only when this URL is supplied." />{draft.whitepaper.chapters.map((chapter, index) => <div key={chapter.number} className="grid gap-4 border border-white/10 p-4"><div className="grid gap-4 md:grid-cols-[90px_1fr]"><Field label="SECTION" value={chapter.number} onChange={(value) => update((content) => { content.whitepaper.chapters[index].number = value; })} /><Field label="TITLE" value={chapter.title} onChange={(value) => update((content) => { content.whitepaper.chapters[index].title = value; })} /></div><Field label="SECTION BODY" value={chapter.body} multiline onChange={(value) => update((content) => { content.whitepaper.chapters[index].body = value; })} /></div>)}</div></Panel>}
        {tab === "community" && <Panel eyebrow="OFFICIAL DESTINATIONS" title="Community channels"><p className="max-w-2xl text-sm leading-6 text-[#9f9b93]">Leave a field empty to retain the public “Coming Soon” state. Only verified official URLs should be published here.</p><div className="grid gap-5"><Field label="SECTION TITLE" value={draft.community.title} onChange={(value) => update((content) => { content.community.title = value; })} /><Field label="SECTION DESCRIPTION" value={draft.community.body} multiline onChange={(value) => update((content) => { content.community.body = value; })} /><Field label="X URL" value={draft.community.xUrl} onChange={(value) => update((content) => { content.community.xUrl = value; })} /><Field label="TELEGRAM URL" value={draft.community.telegramUrl} onChange={(value) => update((content) => { content.community.telegramUrl = value; })} /><Field label="DISCORD URL" value={draft.community.discordUrl} onChange={(value) => update((content) => { content.community.discordUrl = value; })} /></div></Panel>}
      </section>
    </div>
  </div>;
}

export default function Admin() { return <DashboardLayout><AdminGuard /></DashboardLayout>; }
