/** GLORY — Altın Eşik: a managed, web-native whitepaper with an optional verified PDF handoff. */
import { ArrowDownToLine, ArrowLeft, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { BscScanButton, BrandMark, CopyContractButton } from "@/components/glory/Brand";
import { Footer } from "@/components/glory/sections";
import { useGloryContent } from "@/contexts/GloryContentContext";

export default function Whitepaper() {
  const content = useGloryContent();
  return <div className="glory-site min-h-screen bg-[#0d0d0c] text-[#f4f0e8]"><header className="border-b border-white/10 bg-[#0d0d0c]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 sm:px-8 lg:px-12"><Link href="/" className="flex items-center gap-4"><BrandMark /><span className="hidden h-5 w-px bg-white/15 sm:block" /><span className="hidden font-mono text-[10px] tracking-[0.14em] text-[#898680] sm:block">WHITEPAPER</span></Link><Link href="/" className="glory-text-link inline-flex items-center font-mono text-[10px] tracking-[0.14em]"><ArrowLeft className="mr-2 h-3.5 w-3.5" />BACK TO GLORY</Link></div></header><main><section className="technical-surface page-threshold px-5 pb-20 pt-24 sm:px-8 lg:px-12 lg:pb-28 lg:pt-32"><div className="mx-auto max-w-[1000px]"><p className="eyebrow">{content.whitepaper.version}</p><span className="threshold-rule mt-7" aria-hidden="true" /><h1 className="heading-display mt-8 text-5xl leading-[0.9] sm:text-7xl">{content.whitepaper.title}</h1><p className="mt-9 max-w-2xl text-lg leading-8 text-[#aaa69f]">{content.whitepaper.lead}</p><div className="mt-12 flex flex-wrap gap-3"><CopyContractButton /><BscScanButton>VERIFY {content.brand.symbol} CONTRACT</BscScanButton>{content.whitepaper.pdfUrl ? <a href={content.whitepaper.pdfUrl} target="_blank" rel="noopener noreferrer" className="glory-button-outline inline-flex h-11 items-center px-4 font-mono text-[10px] tracking-[0.14em]"><ArrowDownToLine className="mr-2 h-3.5 w-3.5" />DOWNLOAD WHITEPAPER</a> : null}</div></div></section><section className="bg-[#121210] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1000px] gap-12 lg:grid-cols-[180px_1fr]"><aside className="hidden lg:block"><p className="eyebrow sticky top-8">CONTENTS</p></aside><div className="divide-y divide-white/10 border-t border-white/10">{content.whitepaper.chapters.map((chapter) => <article key={chapter.number} className="grid gap-5 py-9 sm:grid-cols-[70px_1fr]"><span className="font-mono text-[10px] tracking-[0.15em] text-[#b9985f]">{chapter.number}</span><div><h2 className="font-display text-3xl font-bold tracking-[-0.05em] text-[#f2ede3]">{chapter.title}</h2><p className="mt-4 max-w-2xl leading-7 text-[#aaa69f]">{chapter.body}</p>{chapter.number === "13" ? <a href={content.contract.bscScanUrl} target="_blank" rel="noopener noreferrer" className="glory-text-link mt-5 inline-flex items-center font-mono text-[10px] tracking-[0.13em]">OPEN VERIFIED CONTRACT <ArrowUpRight className="ml-2 h-4 w-4" /></a> : null}</div></article>)}</div></div></section></main><Footer /></div>;
}
