/** GLORY — Altın Eşik: ecosystem content through material depth, clear claims and threshold motifs. */
import React, { type ReactNode, useState } from "react";
import { Link } from "wouter";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, ArrowUpRight, BadgeCheck, Blocks, ChevronRight, CircleDotDashed, DatabaseZap, Eye, Fingerprint, LockKeyhole, Network, ShieldCheck, UsersRound, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { BscScanButton, BrandMark, CopyContractButton, SectionHeading, VerifiedStatus } from "@/components/glory/Brand";
import { gloryAsset } from "@/const";
import { useGloryContent } from "@/contexts/GloryContentContext";

function Reveal({ children, className = "", delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={className} initial={reduceMotion ? false : { opacity: 0, y: 18, filter: "blur(7px)" }} whileInView={reduceMotion ? {} : { opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.16 }} transition={{ duration: 0.56, delay, ease: [0.23, 1, 0.32, 1] }}>{children}</motion.div>;
}

export function Hero() {
  const reduceMotion = useReducedMotion();
  const content = useGloryContent();
  const [heroImageReady, setHeroImageReady] = useState(false);
  const [heroImageFailed, setHeroImageFailed] = useState(false);
  return <section className="hero-section technical-surface overflow-hidden pt-28 sm:pt-32" aria-labelledby="hero-title"><div className="hero-aura" aria-hidden="true" /><div className="relative mx-auto grid min-h-[690px] max-w-[1440px] items-center px-5 pb-16 sm:px-8 lg:min-h-[760px] lg:grid-cols-[0.88fr_1.12fr] lg:px-12 lg:pb-20"><Reveal className="relative z-10 max-w-3xl pt-12 lg:pt-0"><p className="eyebrow mb-7"><span className="gold-dot" /> {content.hero.eyebrow}</p><h1 id="hero-title" className="heading-display max-w-3xl text-5xl leading-[0.89] text-[#f5f2eb] sm:text-7xl lg:text-[6.4rem] xl:text-[7.55rem]">{content.hero.lineOne}<br /><span className="text-[#c6a66a]">{content.hero.lineTwo}</span><br />{content.hero.lineThree}</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#b4b0a8] sm:text-xl">{content.hero.body}</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><a className="glory-button-gold inline-flex h-12 items-center justify-center px-5 font-mono text-[10px] tracking-[0.14em]" href="#ecosystem">EXPLORE ECOSYSTEM <ArrowRight className="ml-2 h-3.5 w-3.5" /></a><BscScanButton>VIEW {content.brand.symbol}</BscScanButton></div><div className="mt-11 flex flex-wrap items-center gap-x-7 gap-y-3 border-t border-white/10 pt-5 font-mono text-[10px] tracking-[0.12em] text-[#8c8983]"><span>{content.contract.network.toUpperCase()}</span><span className="hidden h-1 w-1 rounded-full bg-[#c6a66a] sm:block" /><span>{content.contract.verified ? "VERIFIED CONTRACT" : "CONTRACT STATUS PENDING"}</span></div></Reveal><motion.div className="relative mt-10 h-[410px] sm:h-[520px] lg:mt-0 lg:h-[670px]" aria-hidden="true" animate={reduceMotion ? {} : { y: [0, -10, 0] }} transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}><div className="hero-prism-orbit hero-prism-orbit-one" /><div className="hero-prism-orbit hero-prism-orbit-two" /><div className="hero-image-frame"><span className="hero-image-fallback" />{!heroImageFailed && <img src={gloryAsset("glory-hero-prism_9c219306.png")} alt="" className={`hero-prism-image ${heroImageReady ? "hero-prism-image-ready" : ""}`} onLoad={() => setHeroImageReady(true)} onError={() => setHeroImageFailed(true)} />}</div><div className="hero-spec-card"><span className="eyebrow">NATIVE UTILITY TOKEN</span><strong>{content.brand.symbol}</strong><div><span>Network</span><b>{content.contract.network}</b></div></div><div className="hero-axis axis-x" /><div className="hero-axis axis-y" /></motion.div></div></section>;
}

export function TrustBar() {
  const content = useGloryContent();
  const claims = [["BNB CHAIN", content.contract.network, Network], ["FIXED SUPPLY", content.contract.totalSupply, DatabaseZap], ["VERIFIED CONTRACT", content.contract.verified ? "Public source code" : "Not available yet", BadgeCheck], [`${content.contract.decimals} DECIMALS`, "BEP-20 compatible", CircleDotDashed]] as const;
  return <section className="border-y border-white/10 bg-[#10100f]" aria-label="GLRY contract foundations"><div className="mx-auto grid max-w-[1440px] divide-y divide-white/10 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4 lg:px-12">{claims.map(([title, description, Icon]) => <div key={title} className="group flex min-h-28 items-center gap-4 px-5 py-6 sm:px-8 lg:px-7"><Icon className="h-5 w-5 text-[#c6a66a] transition-transform duration-300 group-hover:-translate-y-0.5" /><div><p className="font-mono text-[10px] tracking-[0.13em] text-[#e9e3d8]">{title}</p><p className="mt-1 text-sm text-[#898680]">{description}</p></div></div>)}</div><div className="contract-ribbon mx-auto flex max-w-[1440px] flex-col gap-4 px-5 py-5 sm:px-8 lg:flex-row lg:items-center lg:justify-between lg:px-12"><div className="min-w-0"><span className="mr-3 font-mono text-[10px] tracking-[0.12em] text-[#8f8c85]">OFFICIAL CONTRACT</span><code className="block overflow-x-auto pt-1 font-mono text-xs text-[#ded7ca] sm:inline sm:pt-0">{content.contract.address}</code></div><div className="flex shrink-0 flex-wrap gap-3"><CopyContractButton /><BscScanButton /></div></div></section>;
}

export function WhatIsGlory() {
  const content = useGloryContent(); const icons = [Blocks, WalletCards, UsersRound];
  return <section className="section-space bg-[#121210]" id="about"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><Reveal><SectionHeading eyebrow="01 — THE FOUNDATION" title={content.foundation.title} body={content.foundation.body} /></Reveal><div className="mt-16 grid gap-px overflow-hidden border border-white/10 bg-white/10 lg:grid-cols-3">{content.foundation.pillars.map((pillar, position) => { const Icon = icons[position] ?? Blocks; return <Reveal key={pillar.number} delay={position * 0.07} className="glory-panel group min-h-[300px] p-7 sm:p-8"><div className="flex items-start justify-between"><span className="font-mono text-[10px] tracking-[0.16em] text-[#8c8983]">{pillar.number}</span><Icon className="h-5 w-5 text-[#c6a66a]" /></div><div className="mt-20"><h3 className="font-display text-2xl font-bold tracking-[-0.04em] text-[#f4f0e8]">{pillar.title}</h3><p className="mt-4 max-w-sm leading-7 text-[#a7a49d]">{pillar.body}</p></div></Reveal>; })}</div></div></section>;
}

export function EcosystemSection() { const content = useGloryContent(); const [ecosystemImageReady, setEcosystemImageReady] = useState(false); const [ecosystemImageFailed, setEcosystemImageFailed] = useState(false); return <section id="ecosystem" className="section-space technical-surface overflow-hidden"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-12"><Reveal><SectionHeading eyebrow="02 — THE SYSTEM" title={content.ecosystem.title} body={content.ecosystem.body} /><Link href="/6lory" className="glory-text-link mt-9 inline-flex items-center font-mono text-[10px] tracking-[0.14em]">EXPLORE {content.ecosystem.productName.toUpperCase()} <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Reveal><Reveal delay={0.1} className="relative min-h-[400px] lg:min-h-[550px]"><span className="ecosystem-image-fallback" aria-hidden="true" />{!ecosystemImageFailed && <img src={gloryAsset("glory-ecosystem-orbit_ea80c3e9.png")} alt="Abstract connected modules representing the GLORY ecosystem" className={`ecosystem-image ${ecosystemImageReady ? "ecosystem-image-ready" : ""}`} onLoad={() => setEcosystemImageReady(true)} onError={() => setEcosystemImageFailed(true)} />}<div className="ecosystem-core-label"><span className="font-mono text-[9px] tracking-[0.16em] text-[#ae925b]">NATIVE TOKEN</span><strong>{content.brand.symbol}</strong></div><div className="ecosystem-node ecosystem-node-top">REWARDS</div><div className="ecosystem-node ecosystem-node-right">PARTNERS</div><div className="ecosystem-node ecosystem-node-bottom">COMMUNITY</div><div className="ecosystem-node ecosystem-node-left">{content.ecosystem.productName.toUpperCase()}</div></Reveal></div></section>; }

export function TokenSection() { const content = useGloryContent(); const specs = [["Name", content.brand.name], ["Symbol", content.brand.symbol], ["Network", content.contract.network], ["Standard", content.contract.standard], ["Decimals", content.contract.decimals], ["Total Supply", content.contract.totalSupply], ["Verified", content.contract.verified ? "YES" : "NOT AVAILABLE YET"]] as const; const guards = [["Mint Authority", content.contract.mint], ["Owner / Admin", content.contract.owner], ["Tax", content.contract.tax], ["Blacklist", content.contract.blacklist], ["Pause", content.contract.pause]] as const; return <section id="glry" className="section-space bg-[#121210]"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><Reveal><SectionHeading eyebrow="03 — GLRY" title={content.token.title} body={content.token.body} /></Reveal><div className="mt-14 grid gap-8 lg:grid-cols-[1.25fr_0.75fr]"><Reveal className="border border-white/10 bg-[#171614] p-6 sm:p-8"><div className="mb-7 flex items-center justify-between border-b border-white/10 pb-5"><span className="eyebrow">TOKEN SPECIFICATION</span><VerifiedStatus label={content.contract.verified ? "VERIFIED" : "STATUS PENDING"} /></div><dl className="divide-y divide-white/10">{specs.map(([key, value]) => <div key={key} className="grid gap-2 py-4 sm:grid-cols-[180px_1fr] sm:items-center"><dt className="font-mono text-[10px] tracking-[0.12em] text-[#898680]">{key}</dt><dd className="text-sm font-medium text-[#e8e3d9] sm:text-right">{value}</dd></div>)}<div className="grid gap-2 py-4 sm:grid-cols-[180px_1fr] sm:items-center"><dt className="font-mono text-[10px] tracking-[0.12em] text-[#898680]">Contract</dt><dd className="overflow-x-auto font-mono text-xs text-[#d6bd81] sm:text-right">{content.contract.address}</dd></div></dl></Reveal><Reveal delay={0.1} className="flex flex-col border border-[#c6a66a]/25 bg-[#181713] p-6 sm:p-8"><p className="eyebrow">CONTRACT CONTROLS</p><div className="mt-7 space-y-4">{guards.map(([key, value]) => <div key={key} className="flex items-center justify-between"><span className="text-sm text-[#a7a49d]">{key}</span><span className="font-mono text-[11px] tracking-[0.1em] text-[#e8d2a1]">{value}</span></div>)}</div><div className="mt-auto border-t border-white/10 pt-7"><p className="text-sm leading-6 text-[#9c9992]">The deployed token contract does not include these control mechanisms.</p><div className="mt-6 flex flex-wrap gap-3"><CopyContractButton /><BscScanButton>VIEW CONTRACT</BscScanButton></div></div></Reveal></div></div></section>; }

function allocationGradient(items: ReturnType<typeof useGloryContent>["tokenomics"]["allocations"]) { let offset = 0; return `conic-gradient(${items.map((item) => { const start = offset; offset += Number(item.percentage); return `${item.tone} ${start}% ${offset}%`; }).join(", ")})`; }
export function TokenomicsSection() { const content = useGloryContent(); const total = content.tokenomics.allocations.reduce((sum, item) => sum + item.percentage, 0); return <section id="tokenomics" className="section-space technical-surface"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><Reveal><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><SectionHeading eyebrow="04 — PLANNED ALLOCATION" title={content.tokenomics.title} body={content.tokenomics.body} /><div className="border-l border-[#c6a66a] pl-5"><span className="eyebrow">TOTAL SUPPLY</span><p className="mt-2 font-display text-3xl font-bold tracking-[-0.05em] text-[#f1ede4]">{content.contract.totalSupply.replace(",000,000,000", "B").replace(" GLRY", "")} <span className="text-[#c6a66a]">{content.brand.symbol}</span></p></div></div></Reveal><div className="mt-14 grid gap-10 xl:grid-cols-[380px_1fr] xl:gap-20"><Reveal className="flex items-center justify-center"><div className="allocation-ring" style={{ background: allocationGradient(content.tokenomics.allocations) }}><div><span className="eyebrow">PLANNED</span><strong>{total}%</strong><small>ALLOCATION</small></div></div></Reveal><div className="grid gap-x-9 border-t border-white/10 md:grid-cols-2">{content.tokenomics.allocations.map((item, index) => <Reveal delay={index * 0.035} key={`${item.label}-${index}`} className="flex items-center justify-between border-b border-white/10 py-4"><div className="flex items-center gap-3"><span className="h-2.5 w-2.5" style={{ backgroundColor: item.tone }} /><div><p className="text-sm text-[#e7e0d5]">{item.label}</p><p className="mt-1 font-mono text-[10px] tracking-[0.08em] text-[#898680]">{item.amount}{item.label === "Team" ? " · PLANNED VESTING / RELEASE SCHEDULE" : ""}</p></div></div><strong className="font-display text-xl text-[#d7bb7b]">{item.percentage}%</strong></Reveal>)}<Reveal delay={0.3} className="flex items-center justify-between border-b border-[#c6a66a]/50 py-5"><span className="font-mono text-[10px] tracking-[0.14em] text-[#e7dfd2]">TOTAL</span><div className="text-right"><strong className="font-display text-xl text-[#f2ede3]">{total}%</strong><p className="mt-1 font-mono text-[10px] tracking-[0.08em] text-[#bca77a]">{content.contract.totalSupply}</p></div></Reveal></div></div></div></section>; }

export function TransparencySection() { const content = useGloryContent(); const icons = [ShieldCheck, DatabaseZap, LockKeyhole, Fingerprint, Eye]; return <section className="section-space bg-[#121210]" id="transparency"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><Reveal><SectionHeading eyebrow="05 — TRANSPARENCY" title={content.transparency.title} body={content.transparency.body} /></Reveal><div className="mt-14 grid gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-5">{content.transparency.items.map((item, index) => { const Icon = icons[index] ?? Eye; return <Reveal key={`${item.title}-${index}`} delay={index * 0.05} className="glory-panel min-h-[260px] p-6"><Icon className="h-5 w-5 text-[#c6a66a]" /><h3 className="mt-16 font-mono text-[10px] tracking-[0.14em] text-[#ece6dc]">{item.title}</h3><p className="mt-4 text-sm leading-6 text-[#9c9992]">{item.body}</p></Reveal>; })}</div></div></section>; }

export function RoadmapSection() { const content = useGloryContent(); return <section id="roadmap" className="section-space technical-surface overflow-hidden"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><Reveal><SectionHeading eyebrow="06 — ROADMAP" title={content.roadmap.title} body={content.roadmap.body} /></Reveal><div className="mt-16 border-l border-white/10 lg:ml-[20%]">{content.roadmap.phases.map((phase, index) => <Reveal delay={index * 0.06} key={phase.number} className="roadmap-item relative grid gap-6 border-b border-white/10 py-10 pl-8 sm:grid-cols-[minmax(130px,0.4fr)_minmax(160px,0.65fr)_1.3fr] sm:items-start sm:pl-12"><span className="roadmap-pin"><span /></span><p className="font-mono text-[10px] tracking-[0.16em] text-[#9a8256]">PHASE {phase.number}</p><div><h3 className="font-display text-3xl font-bold tracking-[-0.045em] text-[#f3eee5]">{phase.title}</h3><p className={`mt-3 inline-block border px-2 py-1 font-mono text-[9px] tracking-[0.14em] ${phase.status === "COMPLETED" ? "border-[#c6a66a]/50 text-[#d8bd81]" : phase.status === "IN PROGRESS" ? "border-white/20 text-[#e5e0d6]" : "border-white/10 text-[#898680]"}`}>{phase.status}</p></div><ul className="grid gap-2 text-sm text-[#a7a49d]">{phase.entries.map((entry) => <li className="flex gap-2" key={entry}><ChevronRight className="mt-1 h-3.5 w-3.5 shrink-0 text-[#a88956]" />{entry}</li>)}</ul></Reveal>)}</div></div></section>; }

export function WhitepaperCTA() { return <section className="whitepaper-threshold-panel px-5 py-14 sm:px-8 sm:py-20 lg:px-12"><Reveal className="mx-auto flex max-w-[1440px] flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">07 — DOCUMENTATION</p><span className="threshold-rule mt-5" aria-hidden="true" /><h2 className="mt-5 max-w-3xl font-display text-4xl font-bold leading-[0.94] tracking-[-0.06em] text-[#f1ece3] sm:text-6xl">Explore the thinking behind <span className="text-[#c6a66a]">GLORY.</span></h2></div><Link href="/whitepaper" className="glory-button-gold inline-flex h-12 shrink-0 items-center justify-center px-5 font-mono text-[10px] tracking-[0.14em]">READ WHITEPAPER <ArrowRight className="ml-2 h-4 w-4" /></Link></Reveal></section>; }

export function SecuritySection() { const content = useGloryContent(); const details = [["Contract", content.contract.verified ? "Verified" : "Not available yet"], ["Network", content.contract.network], ["Total Supply", content.contract.totalSupply], ["Mint", content.contract.mint], ["Owner", content.contract.owner], ["Tax", content.contract.tax], ["Blacklist", content.contract.blacklist], ["Pause", content.contract.pause]] as const; return <section className="section-space bg-[#121210]"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 sm:px-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-start lg:px-12"><Reveal><SectionHeading eyebrow="08 — SECURITY" title="CONTRACT, CLEARLY." body="Contract information is presented as public, independently verifiable technical data. No wallet connection is required to review GLRY." /><a href={content.contract.bscScanUrl} target="_blank" rel="noopener noreferrer" className="glory-text-link mt-8 inline-flex items-center font-mono text-[10px] tracking-[0.14em]">VIEW VERIFIED CONTRACT <ArrowUpRight className="ml-2 h-4 w-4" /></a></Reveal><Reveal delay={0.1} className="security-terminal"><div className="flex items-center justify-between border-b border-white/10 pb-5"><span className="font-mono text-[10px] tracking-[0.14em] text-[#d6bd81]">{content.brand.symbol} / CONTRACT STATUS</span><span className="h-2 w-2 animate-pulse rounded-full bg-[#c6a66a]" /></div><div className="grid gap-x-12 md:grid-cols-2">{details.map(([label, value]) => <div key={label} className="flex justify-between border-b border-white/10 py-4"><span className="text-sm text-[#a7a49d]">{label}</span><span className="font-mono text-[11px] tracking-[0.08em] text-[#ece7dc]">{value}</span></div>)}</div><div className="mt-6 flex flex-wrap gap-3"><CopyContractButton /><BscScanButton>VIEW ON BSCSCAN</BscScanButton></div></Reveal></div></section>; }

export function CommunitySection() { const content = useGloryContent(); const communities = [["X", "Updates and announcements", content.community.xUrl], ["Telegram", "Community conversation", content.community.telegramUrl], ["Discord", "Ecosystem participation", content.community.discordUrl]] as const; return <section id="community" className="section-space technical-surface"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><Reveal><SectionHeading eyebrow="09 — COMMUNITY" title={content.community.title} body={content.community.body} /></Reveal><div className="mt-14 grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-3">{communities.map(([name, copy, url], index) => <Reveal delay={index * 0.07} key={name} className="glory-panel">{url ? <a href={url} target="_blank" rel="noopener noreferrer" className="group flex min-h-52 w-full flex-col items-start p-7 text-left"><span className="font-mono text-[10px] tracking-[0.16em] text-[#c6a66a]">OFFICIAL CHANNEL</span><strong className="mt-auto font-display text-3xl font-bold tracking-[-0.05em] text-[#f1ece3]">{name}</strong><span className="mt-3 flex items-center text-sm text-[#a7a49d]">{copy}<ArrowUpRight className="ml-2 h-4 w-4 text-[#c6a66a]" /></span></a> : <button onClick={() => toast.message(`${name} coming soon`, { description: "Official GLORY community channels will be published here." })} className="group flex min-h-52 w-full flex-col items-start p-7 text-left"><span className="font-mono text-[10px] tracking-[0.16em] text-[#898680]">COMING SOON</span><strong className="mt-auto font-display text-3xl font-bold tracking-[-0.05em] text-[#f1ece3]">{name}</strong><span className="mt-3 flex items-center text-sm text-[#a7a49d]">{copy}<ArrowUpRight className="ml-2 h-4 w-4 text-[#c6a66a]" /></span></button>}</Reveal>)}</div></div></section>; }

export function Footer() { const content = useGloryContent(); return <footer className="border-t border-white/10 bg-[#0d0d0c]"><div className="mx-auto max-w-[1440px] px-5 pb-9 pt-14 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[1.15fr_0.85fr_1fr]"><div><BrandMark /><p className="mt-6 font-display text-2xl font-bold tracking-[-0.05em] text-[#e9e2d6]">{content.brand.tagline}</p><p className="mt-4 max-w-xs text-sm leading-6 text-[#898680]">{content.hero.body}</p></div><div className="grid grid-cols-2 gap-4"><div><p className="eyebrow mb-5">EXPLORE</p>{[["Ecosystem", "/#ecosystem"], ["GLRY", "/#glry"], ["Tokenomics", "/#tokenomics"], ["Roadmap", "/#roadmap"]].map(([label, href]) => <a href={href} key={label} className="footer-link">{label}</a>)}</div><div><p className="eyebrow mb-5">DOCUMENTS</p><Link href="/whitepaper" className="footer-link">Whitepaper</Link><a href="/#community" className="footer-link">Community</a><a href="/#transparency" className="footer-link">Contract</a></div></div><div className="lg:justify-self-end"><p className="eyebrow mb-5">OFFICIAL CONTRACT</p><code className="block max-w-[320px] break-all font-mono text-xs leading-6 text-[#d6bd81]">{content.contract.address}</code><div className="mt-5"><BscScanButton>VIEW ON BSCSCAN</BscScanButton></div></div></div><div id="risk-disclosure" className="mt-14 grid gap-5 border-t border-white/10 pt-6 text-xs leading-5 text-[#706e69] lg:grid-cols-[1fr_auto]"><p>GLORY communications describe a digital ecosystem and its utility token. They do not constitute an offer, financial advice, or a guarantee of value, income, return or future performance.</p><div className="flex gap-5 font-mono text-[10px] tracking-[0.11em]"><a href="#risk-disclosure" className="hover:text-[#d6bd81]">RISK DISCLOSURE</a><a href="#risk-disclosure" className="hover:text-[#d6bd81]">TERMS</a><a href="#risk-disclosure" className="hover:text-[#d6bd81]">PRIVACY</a></div></div><p className="mt-8 font-mono text-[10px] tracking-[0.13em] text-[#5f5c57]">© 2026 {content.brand.name}</p></div></footer>; }
